#!/bin/bash

# Evaluate the value of an integer 

echo -n "Please enter in an integer -> "
read int

if [[ "$int" =~ ^-?[0-9]+$ ]]; then
    echo "$int is an integer."
    if (( int == 0 )); then
        echo "$int is zero."
    else
        if ((int > 0)); then 
            echo "$int is a positive number."
        else 
            echo "$int is not a negative number."
        fi
        if (( int % 2 == 0 )); then
            echo "$int is an even number."
        else 
            echo "$int is a odd number."
        fi
    fi
else
    echo "$int is not an integer." >&2
    exit 1
fi
