#!/bin/bash 

# guess number 

# range from 1 to 100

random=$(shuf -i1-100 -n1)
#echo "$random"

while true; do
    read -p "Here is the guess number game. Input integer number from 1 to 100, q to quit: "
    if [[ "$REPLY" =~ ^[1-9]$|^[1-9][0-9]$|^100$ ]]; then
        #echo "$REPLY"
        #while [[ "$REPLY" != "$random" ]]; do
        while (( REPLY != random )); do
            if (( REPLY > random )); then 
                echo "Too big"
            else
                echo "Too small"
            fi
            read -p "Try again, enter q to quit: "
            if [[ "$REPLY" != "q" ]]; then
                while [[ ! "$REPLY" =~ ^[1-9]$|^[1-9][0-9]$|^100$ ]]; do
                    echo "$REPLY is invalid value, try integers from 1 to 100."
                    read -p "Try again: " 
                done 
            else
                echo "See you!"
                exit 
            fi
        done
        echo "You win! The answer is $random."
        random=$(shuf -i1-100 -n1)
        continue
    elif [[ "$REPLY" == "q" ]]; then
        echo "See you!" 
        break
    else
        echo "$REPLY is invalid value, try integers from 1 to 100." >&2
        continue
    fi
done












