#!/bin/bash

# read-secret: input a secret passphrase 

if read -t 5 -sp "Enter a secret passphrase in 5 seconds -> " passwd; then
    echo -e "\nInput password is $passwd."

else 
    echo -e "\nTime out!" >&2 
    exit 1
fi

