#!/bin/bash 

# A test menu 

DELAY=2

while [[ "$REPLY" != 0 ]]; do 

    clear    

    cat <<- _EOF_

    Type 1 for display 'Apple'
    Type 2 for display 'Boy'
    Type 3 for display 'Cat'
    Type 4 for display 'Dog'
    Enter 0 to quit

_EOF_

    read -p "Type [0-4]:" 

    if [[ "$REPLY" =~ ^[0-4]?$ ]]; then
        #echo "$REPLY" 
        if (( REPLY == 1 )); then
            echo "Apple"
            sleep $DELAY
        fi
        if (( REPLY == 2 )); then
            echo "Boy"
            sleep $DELAY
        fi
        if (( REPLY == 3 )); then
            echo "Cat"
            sleep $DELAY
        fi
        if (( REPLY == 4 )); then
            echo "Dog"
            sleep $DELAY
        fi
    else 
        echo "Invalid input" >&2 
        sleep $DELAY
    fi

done

echo "Quit"


