#!/bin/bash

# menus exercises 

cat <<- _EOF_ 

Here is a test menus. 
Type 'a' for 'apple' 
Type 'b' for 'banana'
Type 'q/Q' for 'quit'

_EOF_


while true; do 

    read -p "Input:" 

    if [[ $REPLY =~ ^[a,b,q,Q]$ ]];then 
        #echo "$REPLY"
        if [[ "$REPLY" == 'a' ]];then 
            echo ""
            echo "apple"
            echo ""
            continue
        fi
        if [[ "$REPLY" == 'b' ]];then 
            echo ""
            echo "banana"
            echo ""
            continue
        fi    
        if [[ "$REPLY" == 'q' || "$REPLY" == 'Q' ]]; then
            break
        fi
    else 
        echo ""
        echo "Invalid input." >&2 
        echo ""
    fi
done

echo "See you."
