#!/bin/bash
# ul-declare: demonstrate case conversion via declare 

declare -l lower 
declare -u upper 

if [[ -n $1 ]]; then
    lower="$1"
    upper="$1"
    echo "$lower"
    echo "$upper"
    echo ${1,}
    echo ${1,,}
    echo ${1^}
    echo ${1^^}
else
    echo "Wrong" >&2
    exit 1
fi
